version: '2'
services:
  vwadaptor:
    image: virtualwatershed/vwadaptor:v-1.0.0
    ports:
     - "5000:5000"
    volumes:
     - /storage:/vwstorage
  vwaworker:
    image: virtualwatershed/vwadaptor:v-1.0.0
    command: celery -A worker.modelworker worker --loglevel=info
  vwmonitor:
    image: virtualwatershed/vwadaptor:v-1.0.0
    ports:
     - "5555:5555"
    command: flower -A worker.modelworker --port=5555 --broker=redis://redis:6379/0

  vwauth:
    image: virtualwatershed/vw-auth:v-1.0.0
    ports:
     - "5005:5005"
  vwmail:
    image: djfarrelly/maildev
